version: "3.8"

volumes:
  mysql-data:


services:
  web-backend:
    build: ./config/backend
    container_name: web-backend
    ports:
      - "8080:80"
    volumes:
      - ./sources:/var/www/html
      - ./config/backend/php.ini:/usr/local/etc/php/php.ini
      - ./config/httpd_security.conf:/etc/apache2/conf-available/security.conf
    working_dir: /var/www/html
    environment:
      APP_ENV: local
    depends_on:
      - web-mysql
      - web-redis
    restart: always

  web-mysql:
    image: mysql:5.7.43
    container_name: web-mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    restart: always

  web-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: web-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: web-mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - web-mysql
    restart: always

  web-redis:
    image: redis:latest
    container_name: web-redis
    ports:
      - "6379:6379"
    restart: always
